### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by alfahadgm** [gianniacquisto/privateGPT-ui#1]
Hello,

Im getting this error in console when I access the web page :-
Access to XMLHttpRequest at 'http://localhost:8001/v1/ingest/list' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by gianniacquisto** [comment]
Hi this is something you actually need to modify in the settings of your pgpt deployment. There is a CORS setting in your settings.yaml
