### ISSUE TITLE
Error fetching data and missing configuration documentation

### ISSUE THREAD

**Issue by yousecjoe** [gianniacquisto/privateGPT-ui#3]
The UI app is installed but does not connect to PrivateGPT. 

Both the UI and PrivateGPT are running on the same system. 

I can reach PrivateGPT using a hostname, IP, or `localhost`. 
I can reach PrivateGPT from any other system on my network using the IP or hostname. 

However, I can only reach this PrivateGPT UI from the localhost, and only if I use the loopback IP: 127.0.0.1, for example: `http://127.0.0.1:5173/privateGPT-ui/`

Also, when I try to use a `hostname:port` for my PrivateGPT configuration in the UI, I see `AxiosError` `Unsupported protocol <hostname>:` `ERR_BAD_REQUEST`

When I try to set `127.0.0.1:8001` for my PrivateGPT configuration, I see the following error:
`Error fetching data: TypeError: Cannot read properties of undefined (reading 'map') at DocumentList.vue:46:78`

It looks like there is an issue with `instanceIpPort`, but there is no documentation that says how to configure this PrivateGPT UI. 

What is expected in the `Private GPT` text box? Is it localhost? Loopback? Can it be a hostname or the actual IP of the host?  

Thanks for your effort and time.

**Comment by freighty** [comment]
> However, I can only reach this PrivateGPT UI from the localhost, and only if I use the loopback IP: 127.0.0.1, for example: http://127.0.0.1:5173/privateGPT-ui/

You can adjust the listening address by doing:
```
npm run dev -- --host=x.x.x.x
```

Make sure you include both sets of dashes.
