### ISSUE TITLE
API calls don't seem to be happening.

### ISSUE THREAD

**Issue by freighty** [gianniacquisto/privateGPT-ui#4]
Versions:

```
$ nvm version
v20.11.0
$ npm --version
10.2.4
# let me know what else I can put here.
```

Running with `npm run dev` results in a UI, however it doesn't seem to do anything.  Buttons don't work.  Clicking "Add File(s)" interacts with my file manager, but that doesn't seem to upload anywhere on my server.  

No API calls are made despite verifying the accessibility.  I see nothing from PrivateGPT logs.  I see nothing in the UI logs, even when running with `npm run dev --verbose`

I also attempted the same thing by exposing my PrivateGPT instance to the world and using the demo.  No calls reach it, despite being able to remotely curl.

Thanks for reading, let me know what else I can provide.  I'm new to node, so assume the worst. :D

**Comment by gianniacquisto** [comment]
Do you have pgpt running in the background, you also need to enable CORS in PGPT to allow a connection from other urls

**Comment by freighty** [comment]
I do not have it running backgrounded.  I was going to look at running it with nohup, but for now I have it in a screen session.
